version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
    node-app:
        build:
            context: ./
        container_name: node-app
        ports:
            - '8080:8080'
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        ports:
            - '80:80'
        depends_on:
            - node-app
            - mongodb

volumes:
    mongo_data:
